### ISSUE TITLE
Cell is not starting properly when gatewayPort is removed from TCPIngress

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#502]
Below configuration exposes the component as TCP via the cell gateway.
```
 cellery:Component cacheServiceComponent = {
        name: "cache",
        source: {
            image: "redis:alpine"
        },
        ingresses: {
            tcpIngress: <cellery:TCPIngress>{
            backendPort: cacheContainerPort,
            gatewayPort: cacheContainerPort  
           }
        }
    };
```

Inorder to avoid exposing, I removed the gatewayPort from the config as below.
```
 cellery:Component cacheServiceComponent = {
        name: "cache",
        source: {
            image: "redis:alpine"
        },
        ingresses: {
            tcpIngress: <cellery:TCPIngress> {
                backendPort: cacheContainerPort
            }
        }
    };
```
With the above change the component wasn't starting properly, and I could see the cell yaml have below element which says gatewayPort=0, and still exposes in the cell. 
```
...
spec:
  gatewayTemplate:
    metadata:
      creationTimestamp: null
    spec:
      tcp:
      - backendHost: cache
        backendPort: 6379
        port: 0
....
```

Please make the change to remove the entry from the gatewayTemplate if the component is not exposed via the cell gateway (ie, if gatewayPort = 0, don't include into the gatewayTemplate)
